sudo: false

language: node_js 

node_js:
  - node

script: 
  - npm test
cache: 
directories:
  - "node_modules"
     

notifications:
  email: 
    recipients:
      - jayfr.dc@gmail.com 
    
    on_success: always
    on_failure: always