sudo: false

language: node_js 

node_js:
 — “0.10"
install: 
 — npm install -g mocha 
before_script: 
 — sleep 5 # give gulp background task some time to execute. 
script: 
  - npm test
cache: 
directories:
  - "node_modules"
     

notifications:
  email: 
    recipients:
      - jayfr.dc@gmail.com 
    
    on_success: always
    on_failure: always