sudo: false

language: node_js 

node_js:
  - node

install:
  - npm ci

script: 
  - npm test
cache: 
directories:
  - "node_modules"
     

notifications:
  email: 
    recipients:
      - jayfr.dc@gmail.com
      - jfcomparativo@up.edu.ph
    
    on_success: always
    on_failure: always