language: node_js 

node_js:
  - "stable"

cache: 
directories:
  - "node_modules"
    
jobs:
  include:
    - stage: test
      script: ./public/test 

notifications:
  email: 
    recipients:
      - jayfr.dc@gmail.com
      - jfcomparativo@up.edu.ph
    
    on_success: always
    on_failure: always