language: node_js
node_js: '9'

before_script: npm install -g npm@5.8.0

#before_install: |
#  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
#    cd ~/npm && npm install npm
#    cd -
#  } || true
env: PATH=~/npm/node_modules/.bin:$PATH
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

- &smoke
  stage: smoke
  install: npm install --production --no-shrinkwrap
  script: >
    ./bin/mocha --opts /dev/null --reporter spec 
    test/sanity/sanity.spec.js
  cache:
    directories:
      - ~/.npm
      - node_modules

- <<: *smoke
  node_js: '8'

- <<: *smoke
  node_js: '6'

- <<: *smoke
  node_js: '4'

- stage: precache
  script: true

- stage: lint
  script: npm start lint

- script: COVERAGE=1 npm start test.node
  after_success: npm start coveralls

  - &node
  script: npm start test.node
  node_js: '8'

- <<: *node
  node_js: '6'

- <<: *node
  node_js: '4'

- script: npm start test.bundle test.browser
  install: npm ci
  addons:
    artifacts:
      paths:
        - .karma/
        - ./mocha.js
    chrome: stable
    sauce_connect: true




 